# Deploys a wordpress stack using mysql as backend

services:
  wordpress:
    image: wordpress:6.2 
    ports:
      - "80:80"
    networks:
      - frontend
    deploy: 
      replicas: 3
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8.0-debian
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword 
      - MYSQL_USER=kris
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    networks:
      - backend
    ports:
      - "3306:3306"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

volumes:
  dbdata:
  
networks:
  frontend:
  backend:
      