# Creates a Jenkins container with a volume

services:
  jenkins: 
    image: jenkins/jenkins:jdk11
    container_name: container1
    ports:
      - "8080:8080"
    volumes:
      - jenkins-volume:/var/jenkins_home

volumes:
  jenkins-volume: 
  